#!/bin/bash
function guess_b(){
  FNAME=$(echo "$1"| tr '[:upper:]' '[:lower:]'| sed "s/'//g;s/´//g;")
	WORDS=$(echo "${FNAME}" | tr -c '[:alnum:]' ' ' | tr -s ' '|tr ' ' '\n' )
	YEAR=$(echo "${WORDS}" | grep -Eo '\b(((19|20)[0-9][0-9])|2100)'|awk '{$1=$1};1')
	GUESS_TITLE=$(echo "${WORDS}" | grep -e "${YEAR}" -B100 | head -n-1 | tr '\n' ' '|awk '{$1=$1};1')
#	echo "WORDS:${WORDS}"
#	echo "YEAR:${YEAR}"
	#echo "GUESS_TITLE:${GUESS_TITLE}";	echo "GUESS_YEAR:${YEAR}"
	
	[ -z "$GUESS_TITLE" ] || echo "${GUESS_TITLE}+${YEAR}"
}
function before_stop_words() {
	  RESULT=$(echo "$1" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]' ' ' | tr ' ' '\n'  | sed '/^$/d' | egrep -m 1 -e '720|1080p|4k|brrip|webrip|dvdrip|hdrip|tvrip|yify|yts|bitloks|pseudo|fullhd|ettv|hdtv|x264|xvid|juggs' -B100 | head -n -1 | tr '\n' ' ')
	  [ -z "${RESULT}" ] && echo "$1" || echo "${RESULT}"
}
SWORDS=$(before_stop_words "$1")
#echo "SWORDS:${SWORDS}"
GUESS_B=$(guess_b "${SWORDS}")
#echo "GUESS_B:${GUESS_B}"
TT=$(googleSearch "site:imdb.com" "$GUESS_B" "$2" | grep -oP '/tt[0-9]+' | head -n1 | cut -d "/" -f2)
curl -s "http://www.omdbapi.com/?apikey=a681a336&i=${TT}" | jq | tee $1/omdb.json
